// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class HJQCloudCosInitOptions;
@class HJQCloudCosUpdateOptions;
@class HJQCloudCosCredentials;
@class HJQCloudCosUpdateResult;

@interface HJQCloudCosInitOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithRegionName:(NSString *)regionName;
@property(nonatomic, copy) NSString * regionName;
@end

@interface HJQCloudCosUpdateOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTempUploadPath:(NSString *)tempUploadPath
    bucket:(NSString *)bucket
    startTime:(NSNumber *)startTime
    expiredTime:(NSNumber *)expiredTime
    credentials:(HJQCloudCosCredentials *)credentials
    filePath:(NSString *)filePath
    fileName:(NSString *)fileName;
@property(nonatomic, copy) NSString * tempUploadPath;
@property(nonatomic, copy) NSString * bucket;
@property(nonatomic, strong) NSNumber * startTime;
@property(nonatomic, strong) NSNumber * expiredTime;
@property(nonatomic, strong) HJQCloudCosCredentials * credentials;
@property(nonatomic, copy) NSString * filePath;
@property(nonatomic, copy) NSString * fileName;
@end

@interface HJQCloudCosCredentials : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSessionToken:(NSString *)sessionToken
    tmpSecretId:(NSString *)tmpSecretId
    tmpSecretKey:(NSString *)tmpSecretKey;
@property(nonatomic, copy) NSString * sessionToken;
@property(nonatomic, copy) NSString * tmpSecretId;
@property(nonatomic, copy) NSString * tmpSecretKey;
@end

@interface HJQCloudCosUpdateResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPath:(NSString *)path;
@property(nonatomic, copy) NSString * path;
@end

/// The codec used by HJQCloudCosApi.
NSObject<FlutterMessageCodec> *HJQCloudCosApiGetCodec(void);

@protocol HJQCloudCosApi
- (void)initializeOptions:(HJQCloudCosInitOptions *)options error:(FlutterError *_Nullable *_Nonnull)error;
- (void)uploadOptions:(HJQCloudCosUpdateOptions *)options completion:(void(^)(HJQCloudCosUpdateResult *_Nullable, FlutterError *_Nullable))completion;
- (void)multipartUploadOptions:(HJQCloudCosUpdateOptions *)options completion:(void(^)(HJQCloudCosUpdateResult *_Nullable, FlutterError *_Nullable))completion;
@end

extern void HJQCloudCosApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HJQCloudCosApi> *_Nullable api);

NS_ASSUME_NONNULL_END
